# Main configuration file
# Database paths, model names, and other settings

# Database configuration
database:
  type: sqlite # or postgresql, mysql, etc.
  path: "../data/hr_database.db"

# LLM configuration
llm:
  model_name: "gpt-4"
  temperature: 0.1
  max_tokens: 1000

# PDF processing
pdf:
  # LlamaParse configuration
  llama_cloud_api_key: "" # Set in environment variable LLAMA_CLOUD_API_KEY
  result_type: "markdown" # "markdown" or "text"
  num_workers: 4
  language: "en"
  verbose: true

  # Legacy OCR settings (kept for compatibility)
  ocr_enabled: true
  min_confidence: 0.8

# Extraction settings
extraction:
  schema_version: "1.0"
  cache_results: true
